<a href="https://colab.research.google.com/github/johnlex07/Datascience300/blob/main/ejercicio1(24_11_2021).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ejericicio 1.

Creen un vector a entre 5 y 6 con intervalo de 0.2 y guardenlo en formato datos.npy y luego carguenlo con nombre b y muestrelo

In [ ]:
from google.colab import drive
import os
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
%cd '/content/gdrive/MyDrive/bootcamp/Semana 1-20211126T000634Z-001'

/content/gdrive/MyDrive/bootcamp/Semana 1-20211126T000634Z-001


In [21]:
import numpy as np

a=np.arange(5,6,0.2)
print(a.tolist())
a.tofile('datos.npy')
b=np.fromfile('datos.npy')
print(b)





[5.0, 5.2, 5.4, 5.6000000000000005, 5.800000000000001]
[5.  5.2 5.4 5.6 5.8]


Ejercicio 2
Cree un una matriz A con np.array

\begin{equation}
\begin{bmatrix}
1 & 3 & 5\\
11 & 9 & 7\\
13 & 15 & 17
\end{bmatrix}
\end{equation}

Luego de eso utilize el metodo np.sort con el argumento axis =1 or axis=0

A que conclusiones llegan?

In [43]:
A=np.array([[1,3,5],[11,9,7],[13,15,17]])
print(A)
B=np.sort(A,axis=0)
print(B)
C=np.sort(A,axis=1)
print(C)



[[ 1  3  5]
 [11  9  7]
 [13 15 17]]
[[ 1  3  5]
 [11  9  7]
 [13 15 17]]
[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


Ejercicio 3
Cree una matriz de 3x3 B, como la siguiente:
\begin{equation}
\begin{bmatrix}
9 & 1 & 2\\
1 & 9 & 5\\
2 & 5 & 9
\end{bmatrix}
\end{equation}

1. Convierta la matriz a un vector de 1x9
2. Ordene de de menor a mayor el vector
3. Aplique un filtro para extraer solo los numeros menores que 9

In [41]:
A=np.array([[9,1,2],[1,9,5],[2,5,9]])
print(A)
print('parte 1')
print(A.flatten())
print('parte 2')
b=np.sort(A.flatten())
print(b)
print('parte 3')
c=numpy.where(b<9)
print(c)



[[9 1 2]
 [1 9 5]
 [2 5 9]]
parte 1
[9 1 2 1 9 5 2 5 9]
parte 2
[1 1 2 2 5 5 9 9 9]
parte 3
(array([0, 1, 2, 3, 4, 5]),)


Ejercicio 4
Cree una matriz de 3x3 C, como la siguiente:
\begin{equation}
\begin{bmatrix}
1 & 4 & 7\\
2 & 5 & 8\\
3 & 6 & 9
\end{bmatrix}
\end{equation}

1. Calcule la media por cada columna
2. Calcule la media por cada fila
3. Obtenga la media por columnas dandole el doble de peso a la columna con mayores valores de la variable
5. Calcule el percentil 25 por cada columna

In [62]:
C=np.array([[1,4,7],[2,5,8],[3,6,9]])
print(C)
print('parte 1')
print(np.mean(C,axis=1))
print('parte 2')
print(np.mean(C,axis=0))
print('parte 3')
print(np.average(C,axis=1, weights=(1,1,2)))
print('parte 4')
print(np.percentile(C,25,axis=1))


[[1 4 7]
 [2 5 8]
 [3 6 9]]
parte 1
[4. 5. 6.]
parte 2
[2. 5. 8.]
parte 3
[4.75 5.75 6.75]
parte 4
[2.5 3.5 4.5]
